package com.example.ui.util

object Localization {
    private val bangla = mapOf(
        "app_name" to "রিসেলার বিডি",
        "reseller_mode" to "রিসেলার মোড",
        "admin_mode" to "অ্যাডমিন প্যানেল",
        "role_switcher" to "রোল পরিবর্তন করুন",
        "login_title" to "রিসেলার লগইন",
        "phone_hint" to "আপনার মোবাইল নম্বর দিন",
        "login_with_password" to "পাসওয়ার্ড দিয়ে লগইন",
        "login_with_otp" to "ওটিপি দিয়ে লগইন",
        "password" to "পাসওয়ার্ড",
        "password_hint" to "আপনার পাসওয়ার্ড দিন (যেমন: ১২৩৪৫৬)",
        "login_btn" to "লগইন করুন",
        "password_error" to "পাসওয়ার্ড ন্যূনতম ৬ অক্ষরের হতে হবে",
        "phone_error" to "অনুগ্রহ করে সঠিক ১১-সংখ্যার মোবাইল নম্বর দিন",
        "send_otp" to "ওটিপি (OTP) পাঠান",
        "otp_title" to "ওটিপি ভেরিফিকেশন",
        "otp_hint" to "৪ ডিজিটের ওটিপি লিখুন (যেমন: ১২৩৪)",
        "verify_otp" to "ভেরিফাই ওটিপি",
        "or_login" to "অথবা লগইন করুন",
        "google_login" to "গুগল সাইন-ইন",
        "facebook_login" to "ফেসবুক সাইন-ইন",
        "register_now" to "নতুন অ্যাকাউন্ট তৈরি করুন",
        "home" to "হোম",
        "cart" to "কার্ট",
        "my_orders" to "আমার অর্ডার",
        "wallet" to "ওয়ালেট",
        "tutorials" to "ভিডিও ফাইল",
        "support" to "সাপোর্ট",
        "new_products" to "নতুন প্রোডাক্টস",
        "popular_products" to "জনপ্রিয় প্রোডাক্টস",
        "categories" to "ক্যাটাগরি",
        "search_hint" to "প্রোডাক্ট খুঁজুন (নাম বা SKU)",
        "wholesale_price" to "হোলসেল প্রাইস",
        "selling_price" to "বিক্রয় মূল্য",
        "profit" to "আপনার প্রফিট",
        "copy_caption" to "ক্যাপশন কপি করুন",
        "caption_copied" to "ক্যাপশন কপি করা হয়েছে!",
        "download_images" to "ছবি ডাউনলোড করুন",
        "download_videos" to "ভিডিও ডাউনলোড করুন",
        "download_success" to "ডাউনলোড সম্পন্ন হয়েছে!",
        "sku_code" to "এসকেইউ কোড",
        "stock_status" to "স্টক স্ট্যাটাস",
        "in_stock" to "স্টক আছে",
        "out_of_stock" to "স্টক নেই",
        "select_size" to "সাইজ সিলেক্ট করুন",
        "select_color" to "কালার সিলেক্ট করুন",
        "add_to_cart" to "অর্ডারের জন্য কার্ট করুন",
        "checkout" to "অর্ডার প্লেস করুন",
        "customer_name" to "কাস্টমারের নাম",
        "customer_phone" to "মোবাইল নম্বর",
        "district" to "জেলা সিলেক্ট করুন",
        "thana" to "থানা / উপজেলা",
        "full_address" to "কাস্টমারের সম্পূর্ণ ঠিকানা",
        "delivery_instruction" to "ডেলিভারি নির্দেশনা (ঐচ্ছিক)",
        "delivery_charge" to "ডেলিভারি চার্জ",
        "inside_dhaka" to "ঢাকা সিটি (৭০ টাকা)",
        "outside_dhaka" to "ঢাকার বাইরে (১২০ টাকা)",
        "payment_type" to "পেমেন্ট টাইপ",
        "cod" to "ক্যাশ অন ডেলিভারি (সম্পূর্ণ)",
        "advance_delivery" to "ডেলিভারি চার্জ অগ্রিম",
        "full_advance" to "সম্পূর্ণ অগ্রিম পেমেন্ট",
        "payment_method" to "পেমেন্ট গেটওয়ে",
        "first_order_notice" to "নতুন রিসেলার সতর্কতা: আপনার ১ম অর্ডারের জন্য কুরিয়ার চার্জ অগ্রিম প্রদান করা বাধ্যতামূলক!",
        "place_order_btn" to "অর্ডার নিশ্চিত করুন",
        "wallet_balance" to "চলতি ব্যালেন্স",
        "total_profit" to "মোট প্রফিট আয়",
        "total_commission" to "মোট রেফার কমিশন",
        "total_withdrawn" to "মোট উত্তোলন",
        "withdraw_btn" to "উত্তোলন রিকোয়েস্ট",
        "min_withdraw_notice" to "নূন্যতম উত্তোলন ৫০ টাকা।",
        "withdraw_amount" to "উত্তোলনের পরিমাণ (টাকা)",
        "withdraw_number" to "বিকাশ/নগদ/রকেট নম্বর",
        "referral_code" to "আপনার ইউনিক রেফার কোড",
        "invite_friends" to "বন্ধুদের আমন্ত্রণ জানান",
        "referral_rule" to "১.৫% রেফার কমিশন পাবেন প্রতি সফল ও ডেলিভারি হওয়া অর্ডারে (প্রতি ১০০ টাকায় ১.৫০ টাকা কমিশন)।",
        "referral_stats" to "আমন্ত্রিত রিসেলার: %d জন | মোট রেফার আয়: ৳%.2f",
        "chat_placeholder" to "বার্তা লিখুন...",
        "live_chat_title" to "লাইভ সাপোর্ট চ্যাট",
        "admin_dashboard" to "অ্যাডমিন ড্যাশবোর্ড",
        "add_product" to "নতুন প্রোডাক্ট আপলোড",
        "manage_orders" to "অর্ডার ম্যানেজমেন্ট",
        "approve_withdrawals" to "উত্তোলন অনুমোদন",
        "title" to "শিরোনাম",
        "desc" to "বর্ণনা",
        "save" to "সংরক্ষণ করুন",
        "status" to "অর্ডার স্ট্যাটাস",
        "tracking_num" to "ট্র্যাকিং নম্বর",
        "tracking_link" to "ট্র্যাকিং লিংক",
        "leaderboard" to "লিডারবোর্ড",
        "best_resellers" to "সেরা রিসেলার তালিকা",
        "total_orders" to "মোট অর্ডার",
        "reviews" to "ভিডিও রিভিউ",
        "no_orders" to "কোনো অর্ডার পাওয়া যায়নি",
        "orders_count" to "অর্ডার সংখ্যা: %d",
        "pending" to "পেন্ডিং",
        "confirmed" to "কনফার্মড",
        "shipped" to "শিডড",
        "delivered" to "ডেলিভারড",
        "cancelled" to "ক্যান্সেলড",
        "register_title" to "রিসেলার রেজিস্ট্রেশন",
        "name" to "সম্পূর্ণ নাম",
        "name_hint" to "আপনার নাম লিখুন",
        "email" to "জিমেইল এড্রেস",
        "email_hint" to "আপনার জিমেইল দিন",
        "seller_code" to "সেলার কোড এড (যদি থাকে)",
        "seller_code_hint" to "রিসেলারের সেলার কোড দিন",
        "register_btn" to "রেজিস্ট্রেশন সম্পন্ন করুন",
        "email_error" to "সঠিক জিমেইল এড্রেস দিন",
        "name_error" to "অনুগ্রহ করে আপনার নাম লিখুন",
        "otp_verified" to "মোবাইল ওটিপি সফলভাবে ভেরিফাইড!",
        "register_tab" to "রেজিস্ট্রেশন",
        "login_tab" to "লগইন",
        "already_have_account" to "ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন",
        "admin_portal_tab" to "এডমিন পোর্টাল",
        "reseller_portal_tab" to "রিসেলার পোর্টাল",
        "admin_secret_key" to "এডমিন সিক্রেট কি",
        "admin_secret_key_hint" to "মাস্টার এডমিন সিক্রেট কি দিন",
        "admin_register_title" to "এডমিন রেজিস্ট্রেশন",
        "admin_login_title" to "এডমিন লগইন",
        "secret_key_error" to "ভুল সিক্রেট কি! শুধুমাত্র প্রধান এডমিন অ্যাক্সেস পাবেন।",
        "admin_login_btn" to "এডমিন লগইন করুন",
        "select_google_account" to "লগইন করতে একটি গুগল অ্যাকাউন্ট বেছে নিন",
        "add_another_account" to "অন্য কোনো গুগল অ্যাকাউন্ট ব্যবহার করুন",
        "facebook_login_title" to "ফেসবুক দিয়ে লগইন",
        "facebook_identifier" to "ফেসবুক মোবাইল নম্বর বা ইমেইল",
        "facebook_identifier_hint" to "মোবাইল নম্বর বা ইমেইল দিন",
        "facebook_password" to "ফেসবুক পাসওয়ার্ড",
        "facebook_password_hint" to "আপনার ফেসবুক পাসওয়ার্ড দিন",
        "facebook_login_btn" to "ফেসবুক লগইন করুন"
    )

    private val english = mapOf(
        "app_name" to "Reseller BD",
        "reseller_mode" to "Reseller Mode",
        "admin_mode" to "Admin Panel",
        "role_switcher" to "Switch Role",
        "login_title" to "Reseller Login",
        "phone_hint" to "Enter your mobile number",
        "login_with_password" to "Login with Password",
        "login_with_otp" to "Login with OTP",
        "password" to "Password",
        "password_hint" to "Enter your password (e.g., 123456)",
        "login_btn" to "Log In",
        "password_error" to "Password must be at least 6 characters",
        "phone_error" to "Please enter a valid 11-digit mobile number",
        "send_otp" to "Send OTP",
        "otp_title" to "OTP Verification",
        "otp_hint" to "Enter 4 digit OTP (e.g., 1234)",
        "verify_otp" to "Verify OTP",
        "or_login" to "Or Sign In With",
        "google_login" to "Google Sign-In",
        "facebook_login" to "Facebook Sign-In",
        "register_now" to "Register New Account",
        "home" to "Home",
        "cart" to "Cart",
        "my_orders" to "My Orders",
        "wallet" to "Wallet",
        "tutorials" to "Tutorials",
        "support" to "Support",
        "new_products" to "New Products",
        "popular_products" to "Popular Products",
        "categories" to "Categories",
        "search_hint" to "Search product (Name or SKU)",
        "wholesale_price" to "Wholesale Price",
        "selling_price" to "Selling Price",
        "profit" to "Your Profit",
        "copy_caption" to "Copy Caption",
        "caption_copied" to "Caption copied to clipboard!",
        "download_images" to "Download Images",
        "download_videos" to "Download Videos",
        "download_success" to "Downloaded successfully!",
        "sku_code" to "SKU Code",
        "stock_status" to "Stock Status",
        "in_stock" to "In Stock",
        "out_of_stock" to "Out of Stock",
        "select_size" to "Select Size",
        "select_color" to "Select Color",
        "add_to_cart" to "Add to Order Cart",
        "checkout" to "Checkout Order",
        "customer_name" to "Customer Name",
        "customer_phone" to "Mobile Number",
        "district" to "Select District",
        "thana" to "Thana / Upazila",
        "full_address" to "Customer Full Address",
        "delivery_instruction" to "Delivery Instruction (Optional)",
        "delivery_charge" to "Delivery Charge",
        "inside_dhaka" to "Inside Dhaka (70 TK)",
        "outside_dhaka" to "Outside Dhaka (120 TK)",
        "payment_type" to "Payment Type",
        "cod" to "Full Cash On Delivery",
        "advance_delivery" to "Advance Delivery Charge",
        "full_advance" to "Full Advance Payment",
        "payment_method" to "Payment Gateway",
        "first_order_notice" to "New Reseller Warning: For your 1st order, advance payment of courier charge is mandatory!",
        "place_order_btn" to "Confirm Order",
        "wallet_balance" to "Wallet Balance",
        "total_profit" to "Total Profit Earned",
        "total_commission" to "Total Refer Commission",
        "total_withdrawn" to "Total Withdrawn",
        "withdraw_btn" to "Request Withdrawal",
        "min_withdraw_notice" to "Minimum withdrawal amount is 50 Taka.",
        "withdraw_amount" to "Withdrawal Amount (Taka)",
        "withdraw_number" to "bKash/Nagad/Rocket Number",
        "referral_code" to "Your Unique Referral Code",
        "invite_friends" to "Invite Resellers",
        "referral_rule" to "Earn 1.5% referral commission on every successful, delivered order (1.50 Tk commission per 100 Tk order).",
        "referral_stats" to "Invited: %d Resellers | Refer Earnings: ৳%.2f",
        "chat_placeholder" to "Type a message...",
        "live_chat_title" to "Live Support Chat",
        "admin_dashboard" to "Admin Dashboard",
        "add_product" to "Upload New Product",
        "manage_orders" to "Order Management",
        "approve_withdrawals" to "Approve Withdrawals",
        "title" to "Title",
        "desc" to "Description",
        "save" to "Save Details",
        "status" to "Order Status",
        "tracking_num" to "Tracking Number",
        "tracking_link" to "Tracking Link",
        "leaderboard" to "Leaderboard",
        "best_resellers" to "Top Resellers Leaderboard",
        "total_orders" to "Total Orders",
        "reviews" to "Video Reviews",
        "no_orders" to "No orders found",
        "orders_count" to "Orders: %d",
        "pending" to "Pending",
        "confirmed" to "Confirmed",
        "shipped" to "Shipped",
        "delivered" to "Delivered",
        "cancelled" to "Cancelled",
        "register_title" to "Reseller Registration",
        "name" to "Full Name",
        "name_hint" to "Enter your full name",
        "email" to "Gmail Address",
        "email_hint" to "Enter your Gmail address",
        "seller_code" to "Add Seller Code (Optional)",
        "seller_code_hint" to "Enter reseller's seller code",
        "register_btn" to "Complete Registration",
        "email_error" to "Please enter a valid Gmail address",
        "name_error" to "Please enter your name",
        "otp_verified" to "Mobile OTP successfully verified!",
        "register_tab" to "Register",
        "login_tab" to "Login",
        "already_have_account" to "Already have an account? Log In",
        "admin_portal_tab" to "Admin Portal",
        "reseller_portal_tab" to "Reseller Portal",
        "admin_secret_key" to "Admin Secret Key",
        "admin_secret_key_hint" to "Enter Master Admin Secret Key",
        "admin_register_title" to "Admin Registration",
        "admin_login_title" to "Admin Login",
        "secret_key_error" to "Incorrect Secret Key! Only the Master Admin can register.",
        "admin_login_btn" to "Admin Log In",
        "select_google_account" to "Choose a Google account to log in",
        "add_another_account" to "Use another Google account",
        "facebook_login_title" to "Log in with Facebook",
        "facebook_identifier" to "Facebook Mobile Number or Email",
        "facebook_identifier_hint" to "Enter mobile number or email",
        "facebook_password" to "Facebook Password",
        "facebook_password_hint" to "Enter your Facebook password",
        "facebook_login_btn" to "Log In with Facebook"
    )

    private val hindi = mapOf(
        "app_name" to "रीसेलर बीडी",
        "reseller_mode" to "रीसेलर मोड",
        "admin_mode" to "एडमिन पैनल",
        "role_switcher" to "रोल बदलें",
        "login_title" to "रीसेलर लॉगिन",
        "phone_hint" to "अपना मोबाइल नंबर दर्ज करें",
        "login_with_password" to "पासवर्ड से लॉगिन करें",
        "login_with_otp" to "ओटीपी से लॉगिन करें",
        "password" to "पासवर्ड",
        "password_hint" to "अपना पासवर्ड दर्ज करें",
        "login_btn" to "लॉगिन करें",
        "password_error" to "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
        "phone_error" to "कृपया एक वैध 11-अंकों का मोबाइल नंबर दर्ज करें",
        "send_otp" to "ओटीपी भेजें",
        "otp_title" to "ओटीपी सत्यापन",
        "otp_hint" to "4 अंकों का ओटीपी दर्ज करें",
        "verify_otp" to "ओटीपी सत्यापित करें",
        "or_login" to "या साइन इन करें",
        "google_login" to "गूगल साइन-इन",
        "facebook_login" to "फेसबुक साइन-इन",
        "register_now" to "नया खाता बनाएं",
        "home" to "होम",
        "cart" to "कार्ट",
        "my_orders" to "मेरे ऑर्डर",
        "wallet" to "वॉलेट",
        "tutorials" to "वीडियो ट्यूटोरियल",
        "support" to "सपोर्ट",
        "new_products" to "नए उत्पाद",
        "popular_products" to "लोकप्रिय उत्पाद",
        "categories" to "श्रेणियां",
        "search_hint" to "उत्पाद खोजें (नाम या SKU)",
        "wholesale_price" to "होलसेल मूल्य",
        "selling_price" to "बिक्री मूल्य",
        "profit" to "आपका लाभ",
        "copy_caption" to "कैप्शन कॉपी करें",
        "caption_copied" to "कैप्शन कॉपी हो गया!",
        "download_images" to "इमेज डाउनलोड करें",
        "download_videos" to "वीडियो डाउनलोड करें",
        "download_success" to "सफलतापूर्वक डाउनलोड हुआ!",
        "sku_code" to "SKU कोड",
        "stock_status" to "स्टॉक स्थिति",
        "in_stock" to "स्टॉक में है",
        "out_of_stock" to "स्टॉक खत्म",
        "select_size" to "साइज चुनें",
        "select_color" to "रंग चुनें",
        "add_to_cart" to "कार्ट में जोड़ें",
        "checkout" to "ऑर्डर प्लेस करें",
        "customer_name" to "ग्राहक का नाम",
        "customer_phone" to "मोबाइल नंबर",
        "district" to "जिला चुनें",
        "thana" to "थाना / उपजिला",
        "full_address" to "पूरा पता",
        "delivery_instruction" to "डिलीवरी निर्देश (वैकल्पिक)",
        "delivery_charge" to "डिलीवरी शुल्क",
        "inside_dhaka" to "ढाका सिटी (70 टका)",
        "outside_dhaka" to "ढाका के बाहर (120 टका)",
        "payment_type" to "भुगतान प्रकार",
        "cod" to "कैश ऑन डिलीवरी",
        "advance_delivery" to "अग्रिम डिलीवरी शुल्क",
        "full_advance" to "पूर्ण अग्रिम भुगतान",
        "payment_method" to "पेमेंट गेटवे",
        "first_order_notice" to "नए रीसेलर चेतावनी: पहले ऑर्डर के लिए कूरियर शुल्क अग्रिम अनिवार्य है!",
        "place_order_btn" to "ऑर्डर की पुष्टि करें",
        "wallet_balance" to "वॉलेट बैलेंस",
        "total_profit" to "कुल लाभ",
        "total_commission" to "कुल रेफरल कमीशन",
        "total_withdrawn" to "कुल निकासी",
        "withdraw_btn" to "निकासी का अनुरोध",
        "min_withdraw_notice" to "न्यूनतम निकासी राशि 50 टका है।",
        "withdraw_amount" to "निकासी राशि (टका)",
        "withdraw_number" to "bKash/Nagad/Rocket नंबर",
        "referral_code" to "आपका रेफरल कोड",
        "invite_friends" to "मित्रों को आमंत्रित करें",
        "referral_rule" to "प्रत्येक सफल ऑर्डर पर 1.5% कमीशन प्राप्त करें।",
        "referral_stats" to "आमंत्रित: %d रीसेलर | रेफरल आय: ৳%.2f",
        "chat_placeholder" to "संदेश लिखें...",
        "live_chat_title" to "लाइव सपोर्ट चैट",
        "admin_dashboard" to "एडमिन डैशबोर्ड",
        "add_product" to "नया उत्पाद जोड़ें",
        "manage_orders" to "ऑर्डर प्रबंधन",
        "approve_withdrawals" to "निकासी स्वीकृत करें",
        "title" to "शीर्षक",
        "desc" to "विवरण",
        "save" to "सहेजें",
        "status" to "ऑर्डर स्थिति",
        "tracking_num" to "ट्रैकिंग नंबर",
        "tracking_link" to "ट्रैकिंग लिंक",
        "leaderboard" to "लीडरबोर्ड",
        "best_resellers" to "शीर्ष रीसेलर",
        "total_orders" to "कुल ऑर्डर",
        "reviews" to "वीडियो समीक्षाएं",
        "no_orders" to "कोई ऑर्डर नहीं मिला",
        "orders_count" to "ऑर्डर: %d",
        "pending" to "लंबित",
        "confirmed" to "पुष्टि की गई",
        "shipped" to "भेजा गया",
        "delivered" to "डिलीवर हुआ",
        "cancelled" to "रद्द किया गया",
        "register_title" to "रीसेलर पंजीकरण",
        "name" to "पूरा नाम",
        "name_hint" to "अपना नाम दर्ज करें",
        "email" to "जीमेल पता",
        "email_hint" to "अपना जीमेल दर्ज करें",
        "seller_code" to "सेलर कोड (वैकल्पिक)",
        "seller_code_hint" to "रीसेलर कोड दर्ज करें",
        "register_btn" to "पंजीकरण पूरा करें",
        "email_error" to "कृपया वैध जीमेल दर्ज करें",
        "name_error" to "कृपया अपना नाम दर्ज करें",
        "otp_verified" to "ओटीपी सफलतापूर्वक सत्यापित!",
        "register_tab" to "पंजीकरण",
        "login_tab" to "लॉगिन",
        "already_have_account" to "क्या आपके पास पहले से खाता है? लॉगिन करें",
        "admin_portal_tab" to "एडमिन पोर्टल",
        "reseller_portal_tab" to "रीसेलर पोर्टल",
        "admin_secret_key" to "एडमिन सीक्रेट की",
        "admin_secret_key_hint" to "मास्टर एडमिन सीक्रेट की दर्ज करें",
        "admin_register_title" to "एडमिन पंजीकरण",
        "admin_login_title" to "एडमिन लॉगिन",
        "secret_key_error" to "गलत सीक्रेट की!",
        "admin_login_btn" to "एडमिन लॉगिन करें",
        "select_google_account" to "लॉगिन के लिए गूगल खाता चुनें",
        "add_another_account" to "अन्य गूगल खाता उपयोग करें",
        "facebook_login_title" to "फेसबुक से लॉगिन करें",
        "facebook_identifier" to "फेसबुक मोबाइल नंबर या ईमेल",
        "facebook_identifier_hint" to "मोबाइल नंबर या ईमेल दर्ज करें",
        "facebook_password" to "फेसबुक पासवर्ड",
        "facebook_password_hint" to "अपना फेसबुक पासवर्ड दर्ज करें",
        "facebook_login_btn" to "फेसबुक से लॉगिन करें"
    )

    private val urdu = mapOf(
        "app_name" to "ریسیلر بی ڈی",
        "reseller_mode" to "ریسیلر موڈ",
        "admin_mode" to "ایڈمن پینل",
        "role_switcher" to "رول تبدیل کریں",
        "login_title" to "ریسیلر لاگ ان",
        "phone_hint" to "اپنا موبائل نمبر درج کریں",
        "login_with_password" to "پاس ورڈ کے ساتھ لاگ ان",
        "login_with_otp" to "او ٹی پی کے ساتھ لاگ ان",
        "password" to "پاس ورڈ",
        "password_hint" to "اپنا پاس ورڈ درج کریں",
        "login_btn" to "لاگ ان کریں",
        "password_error" to "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے",
        "phone_error" to "براہ کرم صحیح 11 ہندسوں کا موبائل نمبر درج کریں",
        "send_otp" to "او ٹی پی بھیجیں",
        "otp_title" to "او ٹی پی تصدیق",
        "otp_hint" to "4 ہندسوں کا او ٹی پی درج کریں",
        "verify_otp" to "او ٹی پی کی تصدیق کریں",
        "or_login" to "یا سائن ان کریں",
        "google_login" to "گوگل سائن ان",
        "facebook_login" to "فیس بک سائن ان",
        "register_now" to "نیا اکاؤنٹ بنائیں",
        "home" to "ہوم",
        "cart" to "کارٹ",
        "my_orders" to "میرے آرڈرز",
        "wallet" to "والٹ",
        "tutorials" to "ویڈیو ٹیوٹوریل",
        "support" to "سپورٹ",
        "new_products" to "نئی پروڈکٹس",
        "popular_products" to "مقبول پروڈکٹس",
        "categories" to "زمرہ جات",
        "search_hint" to "پروڈکٹ تلاش کریں",
        "wholesale_price" to "ہول سیل قیمت",
        "selling_price" to "فروخت کی قیمت",
        "profit" to "آپ کا منافع",
        "copy_caption" to "کیپشن کاپی کریں",
        "caption_copied" to "کیپشن کاپی ہو گیا!",
        "download_images" to "تصاویر ڈاؤن لوڈ کریں",
        "download_videos" to "ویڈیوز ڈاؤن لوڈ کریں",
        "download_success" to "کامیابی سے ڈاؤن لوڈ ہو گیا!",
        "sku_code" to "ایس کے یو کوڈ",
        "stock_status" to "اسٹاک کی صورتحال",
        "in_stock" to "اسٹاک میں ہے",
        "out_of_stock" to "اسٹاک ختم",
        "select_size" to "سائز منتخب کریں",
        "select_color" to "رنگ منتخب کریں",
        "add_to_cart" to "کارٹ میں شامل کریں",
        "checkout" to "آرڈر مکمل کریں",
        "customer_name" to "گاہک کا نام",
        "customer_phone" to "موبائل نمبر",
        "district" to "ضلع منتخب کریں",
        "thana" to "تحصیل / علاقہ",
        "full_address" to "مکمل پتہ",
        "delivery_instruction" to "ڈلیوری کی ہدایات",
        "delivery_charge" to "ڈلیوری چارجز",
        "inside_dhaka" to "ڈھاکہ سٹی (70 ٹکہ)",
        "outside_dhaka" to "ڈھاکہ سے باہر (120 ٹکہ)",
        "payment_type" to "ادائیگی کی قسم",
        "cod" to "کیش آن ڈلیوری",
        "advance_delivery" to "ایڈوانس ڈلیوری چارجز",
        "full_advance" to "مکمل ایڈوانس ادائیگی",
        "payment_method" to "ادائیگی کا طریقہ",
        "first_order_notice" to "نئے ریسیلر کی اطلاع: پہلے آرڈر پر ڈلیوری چارج ایڈوانس ہونا ضروری ہے!",
        "place_order_btn" to "آرڈر کی تصدیق کریں",
        "wallet_balance" to "والٹ بیلنس",
        "total_profit" to "کل منافع",
        "total_commission" to "کل کمیشن",
        "total_withdrawn" to "کل نکالی گئی رقم",
        "withdraw_btn" to "رقم نکالنے کی درخواست",
        "min_withdraw_notice" to "کم از کم رقم نکالنے کی حد 50 ٹکہ ہے۔",
        "withdraw_amount" to "رقم (ٹکہ)",
        "withdraw_number" to "موبائل والٹ نمبر",
        "referral_code" to "آپ کا ریفرل کوڈ",
        "invite_friends" to "دوستوں کو دعوت دیں",
        "referral_rule" to "ہر کامیاب آرڈر پر 1.5% ریفرل کمیشن حاصل کریں۔",
        "referral_stats" to "دعوت شدہ: %d ریسیلرز | ریفرل آمدنی: ৳%.2f",
        "chat_placeholder" to "پیغام لکھیں...",
        "live_chat_title" to "لائیو سپورٹ چیٹ",
        "admin_dashboard" to "ایڈمن ڈیش بورڈ",
        "add_product" to "نئی پروڈکٹ اپ لوڈ کریں",
        "manage_orders" to "آرڈر مینجمنٹ",
        "approve_withdrawals" to "منظوری دیں",
        "title" to "عنوان",
        "desc" to "تفصیل",
        "save" to "محفوظ کریں",
        "status" to "آرڈر کی صورتحال",
        "tracking_num" to "ٹریکنگ نمبر",
        "tracking_link" to "ٹریکنگ لنک",
        "leaderboard" to "لیڈر بورڈ",
        "best_resellers" to "بہترین ریسیلرز",
        "total_orders" to "کل آرڈرز",
        "reviews" to "ویڈیو ریویوز",
        "no_orders" to "کوئی آرڈر نہیں ملا",
        "orders_count" to "آرڈرز: %d",
        "pending" to "زیر التواء",
        "confirmed" to "تصدیق شدہ",
        "shipped" to "ارسال کر دیا گیا",
        "delivered" to "پہنچا دیا گیا",
        "cancelled" to "منسوخ کر دیا گیا",
        "register_title" to "ریسیلر رجسٹریشن",
        "name" to "پورا نام",
        "name_hint" to "اپنا پورا نام درج کریں",
        "email" to "جی میل ایڈریس",
        "email_hint" to "اپنا جی میل درج کریں",
        "seller_code" to "سیلر کوڈ (اختیاری)",
        "seller_code_hint" to "سیلر کوڈ درج کریں",
        "register_btn" to "رجسٹریشن مکمل کریں",
        "email_error" to "براہ کرم صحیح جی میل درج کریں",
        "name_error" to "براہ کرم اپنا نام درج کریں",
        "otp_verified" to "او ٹی پی کی تصدیق ہو گئی!",
        "register_tab" to "رجسٹریشن",
        "login_tab" to "لاگ ان",
        "already_have_account" to "کیا پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں",
        "admin_portal_tab" to "ایڈمن پورٹل",
        "reseller_portal_tab" to "ریسیلر پورٹل",
        "admin_secret_key" to "ایڈمن سیکرٹ کی",
        "admin_secret_key_hint" to "ماسٹر ایڈمن سیکرٹ کی درج کریں",
        "admin_register_title" to "ایڈمن رجسٹریشن",
        "admin_login_title" to "ایڈمن لاگ ان",
        "secret_key_error" to "غلط سیکرٹ کی!",
        "admin_login_btn" to "ایڈمن لاگ ان",
        "select_google_account" to "لاگ ان کے لیے گوگل اکاؤنٹ منتخب کریں",
        "add_another_account" to "دوسرا گوگل اکاؤنٹ استعمال کریں",
        "facebook_login_title" to "فیس بک سے لاگ ان کریں",
        "facebook_identifier" to "فیس بک موبائل نمبر یا ای میل",
        "facebook_identifier_hint" to "موبائل نمبر یا ای میل درج کریں",
        "facebook_password" to "فیس بک پاس ورڈ",
        "facebook_password_hint" to "اپنا فیس بک پاس ورڈ درج کریں",
        "facebook_login_btn" to "فیس بک سے لاگ ان کریں"
    )


    fun getString(key: String, language: String): String {
        return when (language) {
            "Bangla", "বাংলা" -> bangla[key] ?: key
            "English", "English UK", "English (UK)" -> english[key] ?: key
            "Hindi", "हिंदी" -> hindi[key] ?: english[key] ?: key
            "Urdu", "اردو", "Pakistani", "اردو (پاکستان)" -> urdu[key] ?: english[key] ?: key
            else -> bangla[key] ?: english[key] ?: key
        }
    }
}
